---
- name: workers leave the swarm
  hosts: swarm-workers
  remote_user: ubuntu
  become: true
  become_user: root
  roles:
    - docker-swarm-leave

- name: managers leave the swarm
  hosts: swarm-managers
  remote_user: ubuntu
  become: true
  become_user: root
  roles:
    - docker-swarm-leave
