---
- name: setup pre-requisites
  hosts: all
  remote_user: ubuntu
  become: true
  become_user: root 
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: setup docker user on the nodes
  become: yes
  become_user: docker
  hosts: admin
  roles:
    - configure-admin

- name: copy public key to nodes
  become: yes
  become_user: docker
  hosts: docker-nodes
  roles:
    - copy-keys

- name: install docker
  hosts: docker-nodes
  become: yes
  become_user: root 
  roles:
    - docker-installation

- name: initialize docker swarm
  hosts: swarm-managers
  become: yes
  become_user: root
  roles:
    - docker-swarm-init

- name: add manager to the swarm
  hosts: swarm-managers-cluster
  become: yes
  become_user: root
  roles:
    - docker-swarm-add-manager

- name: add workers to the swarm
  become: yes
  become_user: root 
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
